# Generated by Django 2.0 on 2018-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='enable',
            field=models.CharField(default=True, max_length=256),
        ),
    ]
