# Generated by Django 2.0 on 2018-11-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20181121_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='enable',
        ),
    ]
