# Generated by Django 2.1.3 on 2018-11-20 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authorizationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('line_ie', models.CharField(max_length=50, null=True)),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
    ]
