# Generated by Django 2.0 on 2018-12-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizationmodel',
            name='line_ie',
        ),
        migrations.AddField(
            model_name='authorizationmodel',
            name='line_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='authorizationmodel',
            table='authorization',
        ),
    ]
