# Generated by Django 2.1.3 on 2018-11-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorizationmodel',
            old_name='line_ie',
            new_name='line_id',
        ),
        migrations.AlterModelTable(
            name='authorizationmodel',
            table='authorization',
        ),
    ]
